Repository Kong/developer.konghq.com, pull requests merged in 2025-08, with the labels that each got.

#2392 Generate inso-cli docs
  app/_references/inso-cli/reference/11.4/export.md
  app/_references/inso-cli/reference/11.4/export_spec.md
  app/_references/inso-cli/reference/11.4/generate-docs.md
  app/_references/inso-cli/reference/11.4/index.md
  app/_references/inso-cli/reference/11.4/lint.md
  app/_references/inso-cli/reference/11.4/lint_spec.md
  app/_references/inso-cli/reference/11.4/run.md
  app/_references/inso-cli/reference/11.4/run_collection.md
  app/_references/inso-cli/reference/11.4/run_test.md
  app/_references/inso-cli/reference/11.4/script.md
Labels: release-docs, product:insomnia

#2416 fix: Add AWS vault credential info
  app/_gateway_entities/vault.md
  app/_landing_pages/gateway/secrets-management.yaml
Labels: bug-bash

#2421 Feat(tools): Comparison table for tools
  app/_landing_pages/admin-api.yaml
  app/_landing_pages/deck.yaml
  app/_landing_pages/konnect-api.yaml
  app/_landing_pages/kubernetes-ingress-controller.yaml
  app/_landing_pages/terraform.yaml
  app/_landing_pages/tools.yaml
Labels: bug-bash

#2389 feat(internal-docs): Release checklists for Gateway and Konnect
  docs/README.md
  docs/release-checklists.md
Labels: internal-docs

#2334 feat: Dev Portal v2 migration guide
  app/_indices/dev-portal.yaml
  app/_landing_pages/dev-portal.yaml
  app/dev-portal/breaking-changes.md
  app/dev-portal/v2-migration.md
Labels: product:dev-portal

#2462 Fix: Konnect Gateway compatibility table
  app/_data/support/gateway.yml
Labels: do not merge

#2378 Feat: Migrate Insomnia gRPC page
  .github/styles/base/Dictionary.txt
  app/_indices/insomnia.yaml
  app/insomnia/grpc-requests.md
Labels: product:insomnia

#2403 fix: Change codeblocks to entity_examples in plugin overviews
  app/_kong_plugins/ai-prompt-template/index.md
  app/_kong_plugins/rate-limiting-advanced/index.md
Labels: bug-bash

#2259 doc(kic): upgrade to KIC v3.5
  app/_data/products/kic.yml
  app/_plugins/blocks/kong_config_table.rb
  app/kubernetes-ingress-controller/faq/upgrading-ingress-controller.md
Labels: review:general, team-k8s

#2167 Feat(kic): how to use sticky sessions via UpstreamPolicy
  app/_how-tos/kic-sticky-sessions.md
  app/_includes/k8s/kic-konnect-install.md
  app/_includes/prereqs/products/kic.md
Labels: team-k8s

#2258 doc(kic): deprecate TCP/UDP Ingress CRDs and migration path
  app/_how-tos/kic-proxy-tcp-port.md
  app/_how-tos/kic-proxy-udp.md
  app/kubernetes-ingress-controller/custom-resources.md
  app/kubernetes-ingress-controller/migrate/ingress-to-gateway.md
  app/kubernetes-ingress-controller/migrate/kongingress.md
Labels: review:general, team-k8s

#2536 Fix: Add caution info to Insomnia docs
  app/insomnia/accounts.md
  app/insomnia/allowlist.md
Labels: product:insomnia

#2131 doc(kic): configure sticky session with drain support
  .github/styles/frontmatter/Dictionary.txt
  app/_how-tos/kic-sticky-session-with-drain-support.md
  app/_how-tos/kic-sticky-sessions.md
  app/_includes/prereqs/products/kic.md
  app/_plugins/drops/prereqs.rb
  app/kubernetes-ingress-controller/sticky-sessions-reference.md
Labels: review:general, team-k8s

#2312 Feat: GCP VPC peering on DCGWs
  app/_how-tos/aws-vpc-peering.md
  app/_how-tos/gcp-vpc-peering.md
  app/_includes/prereqs/dedicated-cloud-gateways.md
  app/_landing_pages/dedicated-cloud-gateways.yaml
  app/dedicated-cloud-gateways/reference.md
Labels: do not merge, ci:manual-approve:link-validation

#2584 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: skip-changelog, review:general

#2592 feat(insomnia): Add repo later to Git Sync project in 11.5
  app/_how-tos/synchronize-with-git.md
  app/insomnia/storage.md
Labels: release-docs, product:insomnia

#2611 fix(kic): Support tables and changelog link
  app/_indices/kubernetes-ingress-controller.yaml
  app/kubernetes-ingress-controller/support.md
Labels: product:kic, feedback

#2635 fix(gateway/entities): Fix broken links and missing links in Gateway entities
  app/_gateway_entities/upstream.md
  app/_includes/components/entity_example/format/admin-api.md
  app/_includes/components/entity_example/format/konnect-api.md
  app/_includes/components/entity_example/format/ui.md
Labels: bug

#2641 ko: bump KonnectGatewayControlPlane to v1alpha2
  app/_how-tos/create-transit-gateway-with-operator-and-aws.md
  app/_how-tos/operator-konnect-control-plane-group.md
  app/_how-tos/operator-konnect-control-plane-kic.md
  app/_how-tos/operator-konnect-control-plane-mirror.md
  app/_how-tos/operator-konnect-control-plane.md
  app/_how-tos/operator-konnect-getstarted-controlplane.md
  app/_includes/prereqs/operator/konnect_control_plane.md
  app/operator/konnect/labelling.md
  jekyll.yml
Labels: product:kgo, team-k8s

#2586 feat(service-catalog): Terraform support for integrations and services
  app/_indices/service-catalog.yaml
  app/_landing_pages/service-catalog.yaml
  app/service-catalog/integrations/datadog.md
  app/service-catalog/integrations/swaggerhub.md
  app/service-catalog/integrations/traceable.md
  app/service-catalog/scorecards.md
  app/service-catalog/services.md
Labels: do not merge, release-docs, product:service-catalog

#2572 Release: Insomnia 11.5
  app/_data/products/insomnia.yml
  app/_how-tos/synchronize-with-git.md
  app/_references/inso-cli/reference/11.5/export.md
  app/_references/inso-cli/reference/11.5/export_spec.md
  app/_references/inso-cli/reference/11.5/generate-docs.md
  app/_references/inso-cli/reference/11.5/index.md
  app/_references/inso-cli/reference/11.5/lint.md
  app/_references/inso-cli/reference/11.5/lint_spec.md
  app/_references/inso-cli/reference/11.5/run.md
  app/_references/inso-cli/reference/11.5/run_collection.md
  app/_references/inso-cli/reference/11.5/run_test.md
  app/_references/inso-cli/reference/11.5/script.md
  app/insomnia/external-vault.md
  app/insomnia/import-export.md
  app/insomnia/storage.md
Labels: do not merge, release-docs

#2704 Feat: plugin toolkit process doc
  docs/docs-plugin-toolkit.md
Labels: internal-docs

#2715 Fix: LTS guide typo
  app/_includes/upgrade/lts-changes-34-310.md
Labels: bug

#2697 feat(rate-limiting-advanced): Throttle requests
  app/_kong_plugins/rate-limiting-advanced/examples/throttle-requests.yaml
  app/_kong_plugins/rate-limiting-advanced/index.md
  app/_landing_pages/gateway/rate-limiting.yaml
Labels: do not merge, release-docs, product:gateway

#2728 Fix(decK): Missing decK completion instructions
  app/_landing_pages/deck.yaml
Labels: product:deck
