Repository Kong/developer.konghq.com, pull requests merged in 2025-09, with the labels that each got.

#2630 doc(ko): how to set feature gates and controllers
  .github/styles/frontmatter/Dictionary.txt
  app/_indices/operator.yaml
  app/operator/reference/control-plane-feature-gates-and-controllers.md
Labels: product:kgo

#2782 chore(gateway): Update GPG and RSA keys for 3.12
  app/_data/products/gateway.yml
Labels: product:gateway

#2733 feat(deck): deck file convert for LTS
  app/_how-tos/convert-gateway-lts-2.8-3.4.md
  app/_how-tos/convert-gateway-lts-3.4-3.10.md
  app/_includes/upgrade/lts-upgrade.md
  app/deck/file/convert.md
  app/deck/reference/3.0-upgrade.md
  app/gateway/upgrade/blue-green.md
  app/gateway/upgrade/dual-cluster.md
  app/gateway/upgrade/in-place.md
  app/gateway/upgrade/rolling.md
Labels: ci:manual-approve:link-validation

#2730 feat(gateway): Solace Log plugin
  app/_includes/plugins/logging/log-custom-fields-by-lua.md
  app/_kong_plugins/file-log/index.md
  app/_kong_plugins/http-log/index.md
  app/_kong_plugins/kafka-log/index.md
  app/_kong_plugins/loggly/index.md
  app/_kong_plugins/solace-log/changelog.json
  app/_kong_plugins/solace-log/examples/enable-solace-log.yaml
  app/_kong_plugins/solace-log/index.md
  app/_kong_plugins/solace-log/reference.md
  app/_kong_plugins/syslog/index.md
  app/_kong_plugins/tcp-log/index.md
  app/_kong_plugins/udp-log/index.md
  app/assets/icons/plugins/solace-log.png
Labels: ci:manual-approve:link-validation

#2826 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: skip-changelog, review:general

#2832 doc(ko): configuration option doc for `v2.0.0`
  app/operator/reference/configuration-options.md
Labels: product:kgo

#2869 feat(gateway): add upgrade notes for fallback config importing/exporting
  app/_includes/upgrade/hybrid.md
  app/gateway/cp-outage.md
Labels: review:general, product:gateway

#2881 chore(gateway): 3.12 breaking changes
  app/gateway/breaking-changes.md
Labels: product:gateway

#2897 fix(gateway): Breaking changes version numbers
  app/gateway/breaking-changes.md
Labels: bug, feedback

#2898 fix(gateway): Clearer description for partials
  app/_gateway_entities/partial.md
Labels: feedback

#2910 chore: Note about site generation in docs README
  README.md
Labels: internal-docs

#2924 update(gateway): Benchmark table note
  app/gateway/performance/benchmarks.md
Labels: product:gateway, feedback

#2935 chore(gateway): EOL for Gateway 3.8
  app/_data/products/gateway.yml
  app/_data/support/gateway.yml
  app/gateway/third-party-support.md
  docs/version-eol-or-sunset.md
Labels: product:gateway

#2848 feat(service-catalog): AWS API Gateway integration
  app/_how-tos/discover-and-govern-apis-with-service-catalog.md
  app/_how-tos/discover-aws-gateway-apis-using-konnect-api.md
  app/_how-tos/discover-aws-gateway-apis-using-konnect-ui.md
  app/_includes/prereqs/service-catalog-iam.md
  app/_includes/service-catalog/aws-api-gateway-integration.md
  app/_landing_pages/service-catalog/integrations.yaml
  app/service-catalog/integrations/aws-api-gateway.md
Labels: release-docs

#2987 fix(gateway): Clarify Service explanation
  app/_gateway_entities/service.md
Labels: feedback

#2980 Sync Deck Releases
  app/_data/tools/deck.yml
Labels: skip-changelog, review:general

#2984 Fix (Gateway): Friction Log Get Started
  app/_how-tos/get-started-with-gateway.md
Labels: product:gateway, internal-docs

#2224 feat: Dev Portal: Custom domain certs
  app/dev-portal/custom-domains.md
Labels: release-docs, product:dev-portal

#3020 fix: change `MacOS` to `macOS` to standardize notation
  .github/styles/base/Terms.yml
  app/_how-tos/create-an-insomnia-plugin.md
  app/_how-tos/konnect-reference-platform.md
  app/_includes/tools/deck/install/osx.md
  app/_includes/tools/inso-cli/install/osx.md
  app/_includes/tools/insomnia/install/osx.md
  app/_indices/deck.yaml
  app/_landing_pages/deck.yaml
  app/_landing_pages/inso-cli.yaml
  app/_landing_pages/insomnia.yaml
  app/konnect-reference-platform/orchestrator.md
Labels: ci:manual-approve:link-validation
