Repository Kong/developer.konghq.com, pull requests merged in 2025-07, with the labels that each got.

#2024 Fix: OIDC link
  app/gateway/kong-manager/openid-connect.md
Labels: ci:manual-approve:link-validation, product:gateway

#2056 docs(kafka-consume): add websocket mode to implementation details
  app/_includes/plugins/confluent-kafka-consume/implementation-details.md
  app/_kong_plugins/kafka-consume/index.md
Labels: ci:manual-approve:link-validation

#2013 Feat: Batch LLM requests using llm/v1/files and llm/v1/batches route_type
  .github/styles/base/Dictionary.txt
  app/_data/entity_examples/gateway/routes/batches-route.yml
  app/_data/entity_examples/gateway/routes/files-route.yml
  app/_data/entity_examples/gateway/services/batches-service.yaml
  app/_data/entity_examples/gateway/services/files-service.yaml
  app/_how-tos/send-asychronous-llm-requests.md
Labels: documentation, do not merge, product:ai-gateway

#2047 feat/Add AI Prompt guard plugin how-to
  .github/styles/base/Dictionary.txt
  app/_how-tos/use-ai-prompt-guard-plugin.md
  app/_includes/prereqs/mistral.md
  app/_kong_plugins/ai-prompt-guard/examples/allow-and-deny.yaml
Labels: documentation

#2088 Fix: EOL June 2026 for Amazon Linux 2 for LTS releases.
  app/_data/products/gateway.yml
Labels: review:general

#2079 fix schema validation example for knep
  app/_event_gateway_policies/schema-validation.md
Labels: product:event-gateway

#1983 Dedicated Cloud Gateway domain breaking changes
  app/_landing_pages/dedicated-cloud-gateways.yaml
  app/dedicated-cloud-gateways/breaking-changes.md
  app/dedicated-cloud-gateways/reference.md
Labels: release-docs

#2090 Fix: Event Gateway policies layout
  app/_event_gateway_policies/decrypt.md
  app/_event_gateway_policies/encrypt.md
  app/_event_gateway_policies/modify-headers.md
  app/_event_gateway_policies/schema-validation.md
Labels: product:event-gateway

#1758 Feat: CMEK docs
  app/_landing_pages/konnect.yaml
  app/konnect-platform/cmek.md
Labels: do not merge

#2108 Fix: Clarify that DNS records must be public.
  app/dev-portal/custom-domains.md
Labels: review:general

#2098 feat: add custom domain migrate breaking changes
  app/_landing_pages/dev-portal.yaml
  app/dev-portal/breaking-changes.md
  app/dev-portal/custom-domains.md
Labels: product:dev-portal

#2120 AI Gateway known issue in 3.11
  app/_data/changelogs/gateway.json
  app/_kong_plugins/ai-azure-content-safety/changelog.json
  app/_kong_plugins/ai-prompt-decorator/changelog.json
  app/_kong_plugins/ai-prompt-guard/changelog.json
  app/_kong_plugins/ai-prompt-template/changelog.json
  app/_kong_plugins/ai-proxy-advanced/changelog.json
  app/_kong_plugins/ai-proxy/changelog.json
  app/_kong_plugins/ai-rag-injector/changelog.json
  app/_kong_plugins/ai-rate-limiting-advanced/changelog.json
  app/_kong_plugins/ai-request-transformer/changelog.json
  app/_kong_plugins/ai-response-transformer/changelog.json
  app/_kong_plugins/ai-sanitizer/changelog.json
  app/_kong_plugins/ai-semantic-cache/changelog.json
  app/_kong_plugins/ai-semantic-prompt-guard/changelog.json
  app/_kong_plugins/datakit/changelog.json
  app/gateway/breaking-changes.md
  tools/changelog-generator/missing_entries/3.11.0.0/ai-gateway-license-migration.yml
Labels: priority: high, product:gateway, product:ai-gateway

#2139 Konnect platform feedback
  app/_how-tos/collect-audit-logs.md
  app/_how-tos/collect-dev-portal-audit-logs.md
  app/_how-tos/get-started-with-gateway.md
  app/_indices/konnect-platform.yaml
  app/_landing_pages/konnect.yaml
  app/_redirects
  app/index.html
  app/konnect-platform/audit-logs.md
  app/konnect-platform/notification-hub.md
Labels: priority: high, feedback

#2181 Deck usage and versions
  .github/workflows/sync-deck.yml
  app/_data/tools/deck.yml
  app/_includes/deck/help/file/add-plugins.md
  app/_includes/deck/help/file/add-tags.md
  app/_includes/deck/help/file/convert.md
  app/_includes/deck/help/file/kong2kic.md
  app/_includes/deck/help/file/kong2tf.md
  app/_includes/deck/help/file/lint.md
  app/_includes/deck/help/file/list-tags.md
  app/_includes/deck/help/file/merge.md
  app/_includes/deck/help/file/namespace.md
  app/_includes/deck/help/file/openapi2kong.md
  app/_includes/deck/help/file/patch.md
  app/_includes/deck/help/file/remove-tags.md
  app/_includes/deck/help/file/render.md
  app/_includes/deck/help/file/validate.md
  app/_includes/deck/help/gateway/apply.md
  app/_includes/deck/help/gateway/diff.md
  app/_includes/deck/help/gateway/dump.md
  app/_includes/deck/help/gateway/ping.md
  app/_includes/deck/help/gateway/reset.md
  app/_includes/deck/help/gateway/sync.md
  app/_includes/deck/help/gateway/validate.md
  app/deck/file/convert.md
  app/deck/file/kong2kic.md
  app/deck/file/kong2tf.md
  app/deck/file/lint.md
  app/deck/file/manipulation/namespace.md
  app/deck/file/manipulation/patch.md
  app/deck/file/manipulation/plugins.md
  app/deck/file/manipulation/tags.md
  app/deck/file/merge.md
  app/deck/file/openapi2kong.md
  app/deck/file/render.md
  app/deck/file/validate.md
  app/deck/gateway/apply.md
  app/deck/gateway/diff.md
  app/deck/gateway/dump.md
  app/deck/gateway/ping.md
  app/deck/gateway/reset.md
  app/deck/gateway/sync.md
  app/deck/gateway/validate.md
  tools/deck-versions/README.md
  tools/deck-versions/extract-help.js
  tools/deck-versions/fetch-versions.js
  tools/deck-versions/package-lock.json
  tools/deck-versions/package.json
Labels: feedback

#2222 fix: Redirects for broken links in API spec
  app/_redirects
Labels: feedback

#2046 doc(rbac): include Identity Admin in verbeage for managing RBAC
  app/konnect-platform/teams-and-roles.md
Labels: documentation

#2227 Header cert auth plugin fixes
  api-specs/plugins/header-cert-auth/openapi.yaml
  app/_includes/plugins/manual-consumer-mapping.md
  app/deck/reference/entities.md
Labels: feedback

#2066 chore: KIC 3.5
  app/kubernetes-ingress-controller/customize-image.md
  app/kubernetes-ingress-controller/faq/upgrading-ingress-controller.md
  app/kubernetes-ingress-controller/reference/configuration-options.md
  app/kubernetes-ingress-controller/reference/custom-resources.md
  app/kubernetes-ingress-controller/reference/feature-gates.md
  app/kubernetes-ingress-controller/support.md
  app/kubernetes-ingress-controller/version-compatibility.md
Labels: review:general

#2252 Third-party tools note
  app/gateway/third-party-support.md
Labels: feedback

#2251 fixes: Misc Dev Portal feedback fixes
  app/_includes/konnect/dcr-validate.md
  app/_landing_pages/dev-portal.yaml
  app/dev-portal/analytics.md
  app/dev-portal/apis.md
  app/dev-portal/pages-and-content.md
  app/dev-portal/portal-customization.md
  app/dev-portal/publishing.md
Labels: blocked:sme-response, product:dev-portal

#2289 Known issue: Gateway incremental sync
  app/_data/changelogs/gateway.json
  app/gateway/breaking-changes.md
  tools/changelog-generator/missing_entries/3.10.0.0/incremental-sync-stream-mode.yml
Labels: product:gateway

#2291 Add plugin name in source name format
  app/_includes/plugins/table.html
  app/_plugins/drops/plugins/tabular.rb
Labels: kapa

#2292 Glossary additions
  app/_data/glossary.yml
Labels: kapa

#2296 FAQ for event gateway on-prem
  app/_landing_pages/event-gateway.yaml
Labels: kapa

#2307 Gateway 3.x known issue: Missing Brotli module
  app/_data/changelogs/gateway.json
  app/gateway/breaking-changes.md
  tools/changelog-generator/missing_entries/3.10.0.0/amazonlinux-2-brotli.yml
  tools/changelog-generator/missing_entries/3.11.0.0/amazonlinux-2-brotli.yml
  tools/changelog-generator/missing_entries/3.6.0.0/amazonlinux-2-brotli.yml
  tools/changelog-generator/missing_entries/3.7.0.0/amazonlinux-2-brotli.yml
  tools/changelog-generator/missing_entries/3.8.0.0/amazonlinux-2-brotli.yml
  tools/changelog-generator/missing_entries/3.9.0.0/amazonlinux-2-brotli.yml
Labels: product:gateway

#2333 Update dcg-regions.md
  app/_includes/sections/dcg-regions.md
Labels: review:general

#2368 fix: Dev Portal audit log reference
  app/_indices/dev-portal.yaml
  app/_landing_pages/dev-portal.yaml
  app/konnect-platform/audit-logs.md
Labels: product:dev-portal

#2377 Sync Deck Releases
  app/_data/tools/deck.yml
Labels: skip-changelog, review:general

#2385 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: skip-changelog, review:general

#2297 Update2158 how to download insomnia on windows
  .github/styles/base/Dictionary.txt
  app/_how-tos/download-Insomnia-for-Windows.md
  app/_landing_pages/insomnia.yaml
  app/assets/icons/third-party/mac.svg
  app/assets/icons/third-party/windows.svg
Labels: product:insomnia

#2406 Add missing vault-auth endpoints
  api-specs/plugins/vault-auth/openapi.yaml
Labels: bug-bash

#2405 fix: mem_cache_size link in Resource Guidelines
  app/gateway/resource-sizing-guidelines.md
Labels: bug

#2407 fix(gateway): Broken anchor links to gateway config ref
  app/_gateway_entities/event-hook.md
  app/_gateway_entities/upstream.md
  app/_includes/plugins/rate-limiting/limit-by-ip.md
  app/_includes/sections/data-plane-node-ports.md
  app/ai-gateway/monitor-ai-llm-metrics.md
  app/gateway/breaking-changes.md
  app/gateway/cp-dp-communication.md
  app/gateway/hybrid-mode.md
  app/gateway/kong-manager/configuration.md
  app/gateway/routing/traditional.md
  app/gateway/traditional-mode.md
  app/gateway/traffic-control/proxying.md
  app/gateway/upgrade/backup-and-restore.md
Labels: feedback, bug-bash

#2414 fix: Add guidance for managing Kong Gateway with AWS CDK
  app/_how-tos/kic-install.md
  app/_landing_pages/kubernetes-ingress-controller.yaml
Labels: bug-bash
