Repository Kong/developer.konghq.com, pull requests merged in 2025-05, with the labels that each got.

#1310 Add KIC Vault examples
  .github/styles/frontmatter/Keys.txt
  .github/styles/landing_pages/Components.txt
  app/_how-tos/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity.md
  app/_how-tos/configure-azure-key-vaults-as-a-vault-backend-with-vault-entity.md
  app/_how-tos/configure-google-cloud-secret-as-a-vault-backend.md
  app/_how-tos/kic-vault-aws.md
  app/_how-tos/kic-vault-gcp.md
  app/_how-tos/kic-vault-hashicorp.md
  app/_how-tos/rotate-secrets-in-google-cloud-secret.md
  app/_how-tos/store-the-gateway-database-credentials-with-aws-secrets-manager.md
  app/_includes/card.html
  app/_includes/cleanup/cloud/aws.md
  app/_includes/cleanup/cloud/azure.md
  app/_includes/cleanup/cloud/gcp.md
  app/_includes/cleanup/third-party/aws.md
  app/_includes/cleanup/third-party/azure.md
  app/_includes/cleanup/third-party/google-cloud.md
  app/_includes/components/cleanup.html
  app/_includes/components/prereqs.html
  app/_includes/landing_pages/card.md
  app/_includes/prereqs/cloud/aws.md
  app/_includes/prereqs/cloud/azure.md
  app/_includes/prereqs/cloud/gcp.md
  app/_includes/prereqs/hashicorp-vault-k8s.md
  app/_indices/kubernetes-ingress-controller.yaml
  app/_kong_plugins/redirect/examples/redirect-with-incoming-path.yaml
  app/_landing_pages/gateway/secrets-management.yaml
  tools/track-docs-changes/config/sources.yml
Labels: ci:manual-approve:link-validation

#1414 Changelog for gateway
  app/_landing_pages/gateway.yaml
  app/gateway/changelog.md
Labels: ci:manual-approve:link-validation

#1495 Feat: Private DNS documentation
  app/_how-tos/outbound-dns-resolver.md
  app/_how-tos/private-hosted-zones.md
  app/_includes/prereqs/aws-cli.md
  app/dedicated-cloud-gateways/reference.md
  app/serverless-gateways/index.md
Labels: do not merge

#1589 [Fix] Added limitations of Active Tracing to certain Gateway types
  app/konnect-platform/active-tracing.md
Labels: review:general

#1598 Update dedicated-cloud-gateways.yaml
  app/_landing_pages/dedicated-cloud-gateways.yaml
Labels: review:general

#1649 Performance docs
  .github/styles/base/Dictionary.txt
  app/_indices/gateway.yaml
  app/gateway/network/dns-config-reference.md
  app/gateway/performance/benchmarks.md
  app/gateway/performance/establish-a-benchmark.md
  app/gateway/performance/optimize.md
  tools/track-docs-changes/config/sources.yml
Labels: ci:manual-approve:link-validation

#1664 Fix: Kong Gateway ports reference
  app/gateway/network/index.md
Labels: product:gateway
